namespace: awx

resources:
  - ../base/

helmCharts:
- name: awx-operator
  repo: https://ansible-community.github.io/awx-operator-helm/
  version: 2.19.1
  releaseName: awx-operator
  namespace: awx
  valuesFile: values.yaml
  includeCRDs: true
