namespace: awx

resources:
  - ../base/

helmCharts:
- name: ansible-awx-operator 
  repo: https://ansible.github.io/awx-operator/
  version: 2.4.0 #1.3.0
  releaseName: ansible-awx-operator 
  namespace: awx
  valuesFile: values.yaml
  includeCRDs: true