apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: ansible-awx
  namespace: awx
spec:
  service_type: LoadBalancer
  service_annotations: '{"metallb.universe.tf/loadBalancerIPs": "192.168.2.212"}'
