apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx-postgresql
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/pve/proxmox/awx-postgresql
    server: 192.168.2.180
