# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-13-ansible-awx-postgres-13-0
#   namespace: awx
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs-storage
#   resources:
#     requests:
#       storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-15-ansible-awx-postgres-15-0
  namespace: awx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-storage
